using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PoolManager : MonoBehaviour {

    Dictionary<int, Queue<PoolObject>> poolDictionary = new Dictionary<int, Queue<PoolObject>>();

    static PoolManager _instance;

    public static PoolManager instance
    {
        get
        {
            if (_instance == null)
                _instance = FindObjectOfType<PoolManager>();
            return _instance;
        }
    }

    private void Awake()
    {
        if (_instance == null)
        {
            _instance = this;
        }
        else
        {
            if (_instance != this)
                Destroy(gameObject);
            else
                DontDestroyOnLoad(gameObject);
        }
    }

    [SerializeField]
    int defaultPoolSize = 20;

    // overloaded CreatePool method that creates a pool of prefabs of size defaultPoolSize
    public void CreatePool(GameObject prefab) {
        CreatePool(prefab, defaultPoolSize);
    }

    public void CreatePool(GameObject prefab, int poolSize) {
        int poolKey = prefab.GetInstanceID();       

        if (!poolDictionary.ContainsKey(poolKey)) {
            GameObject poolHolder = new GameObject(prefab.name + "pool");
            poolHolder.transform.parent = this.transform;
            Queue<PoolObject> queue = new Queue<PoolObject>();

            for (int i = 0; i < poolSize; i++) {
                GameObject obj = Instantiate(prefab);
                PoolObject po = new PoolObject(obj);
                queue.Enqueue(po);
                po.SetParent(poolHolder.transform);
            }
            poolDictionary.Add(poolKey, queue);
        }

    }

    public GameObject ReuseObject(GameObject prefab, Vector3 position, Quaternion rotation) {
        int poolKey = prefab.GetInstanceID();

        if (poolDictionary.ContainsKey(poolKey)){
            PoolObject target = poolDictionary[poolKey].Dequeue();
            poolDictionary[poolKey].Enqueue(target);

            return target.Reuse(position, rotation);
        } else
        {
            Debug.Log(string.Format("Prefab {0} does not have a pool. Remember to create one first!", prefab.name));
            return null;
        }
    }

    class PoolObject
    {
        GameObject gameObject;
        Transform transform;

        // an array of IPoolables generated by the constructor, allows for
        // efficient access to components that require 'resetting' when reused
        IPoolable[] poolableComponents;


        public PoolObject(GameObject instance)
        {
            this.gameObject = instance;
            this.transform = gameObject.transform;
            gameObject.SetActive(false);

            poolableComponents = gameObject.GetComponents<IPoolable>();
        }

        public GameObject Reuse(Vector3 position, Quaternion rotation, bool active = false) {
            transform.position = position;
            transform.rotation = rotation;

            foreach (IPoolable pool in poolableComponents){
                pool.OnReuse();
            }

            gameObject.SetActive(active); 
            return gameObject;
        }

        public void SetParent(Transform parent){
            transform.parent = parent;
        }
    }

}
